// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/server_service/server_service.proto

package server_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerStatus int32

const (
	ServerStatus_SERVER_STATUS_UNSPECIFIED ServerStatus = 0
	ServerStatus_SERVER_STATUS_ON          ServerStatus = 1
	ServerStatus_SERVER_STATUS_OFF         ServerStatus = 2
	ServerStatus_SERVER_STATUS_UNDEFINED   ServerStatus = 3
)

// Enum value maps for ServerStatus.
var (
	ServerStatus_name = map[int32]string{
		0: "SERVER_STATUS_UNSPECIFIED",
		1: "SERVER_STATUS_ON",
		2: "SERVER_STATUS_OFF",
		3: "SERVER_STATUS_UNDEFINED",
	}
	ServerStatus_value = map[string]int32{
		"SERVER_STATUS_UNSPECIFIED": 0,
		"SERVER_STATUS_ON":          1,
		"SERVER_STATUS_OFF":         2,
		"SERVER_STATUS_UNDEFINED":   3,
	}
)

func (x ServerStatus) Enum() *ServerStatus {
	p := new(ServerStatus)
	*p = x
	return p
}

func (x ServerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_server_service_server_service_proto_enumTypes[0].Descriptor()
}

func (ServerStatus) Type() protoreflect.EnumType {
	return &file_proto_server_service_server_service_proto_enumTypes[0]
}

func (x ServerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerStatus.Descriptor instead.
func (ServerStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_server_service_server_service_proto_rawDescGZIP(), []int{0}
}

type ServerListSortOrder_Values int32

const (
	ServerListSortOrder_SERVER_ID_ASC    ServerListSortOrder_Values = 0
	ServerListSortOrder_SERVER_ID_DESC   ServerListSortOrder_Values = 1
	ServerListSortOrder_SERVER_NAME_ASC  ServerListSortOrder_Values = 2
	ServerListSortOrder_SERVER_NAME_DESC ServerListSortOrder_Values = 3
	ServerListSortOrder_STATUS_ASC       ServerListSortOrder_Values = 4
	ServerListSortOrder_STATUS_DESC      ServerListSortOrder_Values = 5
	ServerListSortOrder_IPV4_ASC         ServerListSortOrder_Values = 6
	ServerListSortOrder_IPV4_DESC        ServerListSortOrder_Values = 7
	ServerListSortOrder_LOCATION_ASC     ServerListSortOrder_Values = 8
	ServerListSortOrder_LOCATION_DESC    ServerListSortOrder_Values = 9
	ServerListSortOrder_OS_ASC           ServerListSortOrder_Values = 10
	ServerListSortOrder_OS_DESC          ServerListSortOrder_Values = 11
	ServerListSortOrder_CREATED_AT_ASC   ServerListSortOrder_Values = 12
	ServerListSortOrder_CREATED_AT_DESC  ServerListSortOrder_Values = 13
)

// Enum value maps for ServerListSortOrder_Values.
var (
	ServerListSortOrder_Values_name = map[int32]string{
		0:  "SERVER_ID_ASC",
		1:  "SERVER_ID_DESC",
		2:  "SERVER_NAME_ASC",
		3:  "SERVER_NAME_DESC",
		4:  "STATUS_ASC",
		5:  "STATUS_DESC",
		6:  "IPV4_ASC",
		7:  "IPV4_DESC",
		8:  "LOCATION_ASC",
		9:  "LOCATION_DESC",
		10: "OS_ASC",
		11: "OS_DESC",
		12: "CREATED_AT_ASC",
		13: "CREATED_AT_DESC",
	}
	ServerListSortOrder_Values_value = map[string]int32{
		"SERVER_ID_ASC":    0,
		"SERVER_ID_DESC":   1,
		"SERVER_NAME_ASC":  2,
		"SERVER_NAME_DESC": 3,
		"STATUS_ASC":       4,
		"STATUS_DESC":      5,
		"IPV4_ASC":         6,
		"IPV4_DESC":        7,
		"LOCATION_ASC":     8,
		"LOCATION_DESC":    9,
		"OS_ASC":           10,
		"OS_DESC":          11,
		"CREATED_AT_ASC":   12,
		"CREATED_AT_DESC":  13,
	}
)

func (x ServerListSortOrder_Values) Enum() *ServerListSortOrder_Values {
	p := new(ServerListSortOrder_Values)
	*p = x
	return p
}

func (x ServerListSortOrder_Values) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerListSortOrder_Values) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_server_service_server_service_proto_enumTypes[1].Descriptor()
}

func (ServerListSortOrder_Values) Type() protoreflect.EnumType {
	return &file_proto_server_service_server_service_proto_enumTypes[1]
}

func (x ServerListSortOrder_Values) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerListSortOrder_Values.Descriptor instead.
func (ServerListSortOrder_Values) EnumDescriptor() ([]byte, []int) {
	return file_proto_server_service_server_service_proto_rawDescGZIP(), []int{0, 0}
}

type ServerListSortOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerListSortOrder) Reset() {
	*x = ServerListSortOrder{}
	mi := &file_proto_server_service_server_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerListSortOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerListSortOrder) ProtoMessage() {}

func (x *ServerListSortOrder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_service_server_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerListSortOrder.ProtoReflect.Descriptor instead.
func (*ServerListSortOrder) Descriptor() ([]byte, []int) {
	return file_proto_server_service_server_service_proto_rawDescGZIP(), []int{0}
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerName    string                 `protobuf:"bytes,3,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Status        ServerStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=ServerStatus" json:"status,omitempty"`
	Ipv4          string                 `protobuf:"bytes,5,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	Os            string                 `protobuf:"bytes,8,opt,name=os,proto3" json:"os,omitempty"`
	IntervalTime  int64                  `protobuf:"varint,9,opt,name=interval_time,json=intervalTime,proto3" json:"interval_time,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_proto_server_service_server_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_service_server_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_proto_server_service_server_service_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Server) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Server) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *Server) GetStatus() ServerStatus {
	if x != nil {
		return x.Status
	}
	return ServerStatus_SERVER_STATUS_UNSPECIFIED
}

func (x *Server) GetIpv4() string {
	if x != nil {
		return x.Ipv4
	}
	return ""
}

func (x *Server) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Server) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Server) GetIntervalTime() int64 {
	if x != nil {
		return x.IntervalTime
	}
	return 0
}

func (x *Server) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ServerListFilterOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerName    string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Status        ServerStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=ServerStatus" json:"status,omitempty"`
	Ipv4          string                 `protobuf:"bytes,4,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Os            string                 `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerListFilterOptions) Reset() {
	*x = ServerListFilterOptions{}
	mi := &file_proto_server_service_server_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerListFilterOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerListFilterOptions) ProtoMessage() {}

func (x *ServerListFilterOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_service_server_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerListFilterOptions.ProtoReflect.Descriptor instead.
func (*ServerListFilterOptions) Descriptor() ([]byte, []int) {
	return file_proto_server_service_server_service_proto_rawDescGZIP(), []int{2}
}

func (x *ServerListFilterOptions) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerListFilterOptions) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ServerListFilterOptions) GetStatus() ServerStatus {
	if x != nil {
		return x.Status
	}
	return ServerStatus_SERVER_STATUS_UNSPECIFIED
}

func (x *ServerListFilterOptions) GetIpv4() string {
	if x != nil {
		return x.Ipv4
	}
	return ""
}

func (x *ServerListFilterOptions) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ServerListFilterOptions) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

type ServerListPagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint32                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SortOrder     *ServerListSortOrder   `protobuf:"bytes,3,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerListPagination) Reset() {
	*x = ServerListPagination{}
	mi := &file_proto_server_service_server_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerListPagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerListPagination) ProtoMessage() {}

func (x *ServerListPagination) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_service_server_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerListPagination.ProtoReflect.Descriptor instead.
func (*ServerListPagination) Descriptor() ([]byte, []int) {
	return file_proto_server_service_server_service_proto_rawDescGZIP(), []int{3}
}

func (x *ServerListPagination) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ServerListPagination) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ServerListPagination) GetSortOrder() *ServerListSortOrder {
	if x != nil {
		return x.SortOrder
	}
	return nil
}

type CreateServerRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServerId          string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerName        string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Ipv4              string                 `protobuf:"bytes,3,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Location          string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Os                string                 `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	IntervalCheckTime uint32                 `protobuf:"varint,6,opt,name=interval_check_time,json=intervalCheckTime,proto3" json:"interval_check_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateServerRequest) Reset() {
	*x = CreateServerRequest{}
	mi := &file_proto_server_service_server_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerRequest) ProtoMessage() {}

func (x *CreateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_service_server_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerRequest.ProtoReflect.Descriptor instead.
func (*CreateServerRequest) Descriptor() ([]byte, []int) {
	return file_proto_server_service_server_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateServerRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CreateServerRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *CreateServerRequest) GetIpv4() string {
	if x != nil {
		return x.Ipv4
	}
	return ""
}

func (x *CreateServerRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateServerRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *CreateServerRequest) GetIntervalCheckTime() uint32 {
	if x != nil {
		return x.IntervalCheckTime
	}
	return 0
}

type CreateServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServerResponse) Reset() {
	*x = CreateServerResponse{}
	mi := &file_proto_server_service_server_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerResponse) ProtoMessage() {}

func (x *CreateServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_service_server_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerResponse.ProtoReflect.Descriptor instead.
func (*CreateServerResponse) Descriptor() ([]byte, []int) {
	return file_proto_server_service_server_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateServerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ViewServerRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Offset        uint32                     `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint32                     `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Filter        *ServerListFilterOptions   `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	SortOrder     ServerListSortOrder_Values `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3,enum=ServerListSortOrder_Values" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewServerRequest) Reset() {
	*x = ViewServerRequest{}
	mi := &file_proto_server_service_server_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewServerRequest) ProtoMessage() {}

func (x *ViewServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_service_server_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewServerRequest.ProtoReflect.Descriptor instead.
func (*ViewServerRequest) Descriptor() ([]byte, []int) {
	return file_proto_server_service_server_service_proto_rawDescGZIP(), []int{6}
}

func (x *ViewServerRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ViewServerRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ViewServerRequest) GetFilter() *ServerListFilterOptions {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ViewServerRequest) GetSortOrder() ServerListSortOrder_Values {
	if x != nil {
		return x.SortOrder
	}
	return ServerListSortOrder_SERVER_ID_ASC
}

type ViewServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*Server              `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	TotalCount    uint32                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewServerResponse) Reset() {
	*x = ViewServerResponse{}
	mi := &file_proto_server_service_server_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewServerResponse) ProtoMessage() {}

func (x *ViewServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_service_server_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewServerResponse.ProtoReflect.Descriptor instead.
func (*ViewServerResponse) Descriptor() ([]byte, []int) {
	return file_proto_server_service_server_service_proto_rawDescGZIP(), []int{7}
}

func (x *ViewServerResponse) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *ViewServerResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UpdateServerRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServerName        string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Ipv4              string                 `protobuf:"bytes,2,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Location          string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Os                string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	IntervalCheckTime uint32                 `protobuf:"varint,5,opt,name=interval_check_time,json=intervalCheckTime,proto3" json:"interval_check_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateServerRequest) Reset() {
	*x = UpdateServerRequest{}
	mi := &file_proto_server_service_server_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerRequest) ProtoMessage() {}

func (x *UpdateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_service_server_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerRequest.ProtoReflect.Descriptor instead.
func (*UpdateServerRequest) Descriptor() ([]byte, []int) {
	return file_proto_server_service_server_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateServerRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *UpdateServerRequest) GetIpv4() string {
	if x != nil {
		return x.Ipv4
	}
	return ""
}

func (x *UpdateServerRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateServerRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *UpdateServerRequest) GetIntervalCheckTime() uint32 {
	if x != nil {
		return x.IntervalCheckTime
	}
	return 0
}

type UpdateServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServerResponse) Reset() {
	*x = UpdateServerResponse{}
	mi := &file_proto_server_service_server_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerResponse) ProtoMessage() {}

func (x *UpdateServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_service_server_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerResponse.ProtoReflect.Descriptor instead.
func (*UpdateServerResponse) Descriptor() ([]byte, []int) {
	return file_proto_server_service_server_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateServerResponse) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

type DeleteServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerRequest) Reset() {
	*x = DeleteServerRequest{}
	mi := &file_proto_server_service_server_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerRequest) ProtoMessage() {}

func (x *DeleteServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_service_server_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerRequest.ProtoReflect.Descriptor instead.
func (*DeleteServerRequest) Descriptor() ([]byte, []int) {
	return file_proto_server_service_server_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteServerRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type DeleteServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerResponse) Reset() {
	*x = DeleteServerResponse{}
	mi := &file_proto_server_service_server_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerResponse) ProtoMessage() {}

func (x *DeleteServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_service_server_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerResponse.ProtoReflect.Descriptor instead.
func (*DeleteServerResponse) Descriptor() ([]byte, []int) {
	return file_proto_server_service_server_service_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteServerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ImportServersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*Server              `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportServersRequest) Reset() {
	*x = ImportServersRequest{}
	mi := &file_proto_server_service_server_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportServersRequest) ProtoMessage() {}

func (x *ImportServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_service_server_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportServersRequest.ProtoReflect.Descriptor instead.
func (*ImportServersRequest) Descriptor() ([]byte, []int) {
	return file_proto_server_service_server_service_proto_rawDescGZIP(), []int{12}
}

func (x *ImportServersRequest) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

type ImportServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  uint32                 `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	SuccessIds    []string               `protobuf:"bytes,2,rep,name=success_ids,json=successIds,proto3" json:"success_ids,omitempty"`
	FailureCount  uint32                 `protobuf:"varint,3,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	FailureIds    []string               `protobuf:"bytes,4,rep,name=failure_ids,json=failureIds,proto3" json:"failure_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportServersResponse) Reset() {
	*x = ImportServersResponse{}
	mi := &file_proto_server_service_server_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportServersResponse) ProtoMessage() {}

func (x *ImportServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_service_server_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportServersResponse.ProtoReflect.Descriptor instead.
func (*ImportServersResponse) Descriptor() ([]byte, []int) {
	return file_proto_server_service_server_service_proto_rawDescGZIP(), []int{13}
}

func (x *ImportServersResponse) GetSuccessCount() uint32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *ImportServersResponse) GetSuccessIds() []string {
	if x != nil {
		return x.SuccessIds
	}
	return nil
}

func (x *ImportServersResponse) GetFailureCount() uint32 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *ImportServersResponse) GetFailureIds() []string {
	if x != nil {
		return x.FailureIds
	}
	return nil
}

type ExportServersRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Filter        *ServerListFilterOptions `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportServersRequest) Reset() {
	*x = ExportServersRequest{}
	mi := &file_proto_server_service_server_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportServersRequest) ProtoMessage() {}

func (x *ExportServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_service_server_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportServersRequest.ProtoReflect.Descriptor instead.
func (*ExportServersRequest) Descriptor() ([]byte, []int) {
	return file_proto_server_service_server_service_proto_rawDescGZIP(), []int{14}
}

func (x *ExportServersRequest) GetFilter() *ServerListFilterOptions {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ExportServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*Server              `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportServersResponse) Reset() {
	*x = ExportServersResponse{}
	mi := &file_proto_server_service_server_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportServersResponse) ProtoMessage() {}

func (x *ExportServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_service_server_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportServersResponse.ProtoReflect.Descriptor instead.
func (*ExportServersResponse) Descriptor() ([]byte, []int) {
	return file_proto_server_service_server_service_proto_rawDescGZIP(), []int{15}
}

func (x *ExportServersResponse) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

var File_proto_server_service_server_service_proto protoreflect.FileDescriptor

const file_proto_server_service_server_service_proto_rawDesc = "" +
	"\n" +
	")proto/server_service/server_service.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x02\n" +
	"\x13ServerListSortOrder\"\xff\x01\n" +
	"\x06Values\x12\x11\n" +
	"\rSERVER_ID_ASC\x10\x00\x12\x12\n" +
	"\x0eSERVER_ID_DESC\x10\x01\x12\x13\n" +
	"\x0fSERVER_NAME_ASC\x10\x02\x12\x14\n" +
	"\x10SERVER_NAME_DESC\x10\x03\x12\x0e\n" +
	"\n" +
	"STATUS_ASC\x10\x04\x12\x0f\n" +
	"\vSTATUS_DESC\x10\x05\x12\f\n" +
	"\bIPV4_ASC\x10\x06\x12\r\n" +
	"\tIPV4_DESC\x10\a\x12\x10\n" +
	"\fLOCATION_ASC\x10\b\x12\x11\n" +
	"\rLOCATION_DESC\x10\t\x12\n" +
	"\n" +
	"\x06OS_ASC\x10\n" +
	"\x12\v\n" +
	"\aOS_DESC\x10\v\x12\x12\n" +
	"\x0eCREATED_AT_ASC\x10\f\x12\x13\n" +
	"\x0fCREATED_AT_DESC\x10\r\"\x9d\x02\n" +
	"\x06Server\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x1f\n" +
	"\vserver_name\x18\x03 \x01(\tR\n" +
	"serverName\x12%\n" +
	"\x06status\x18\x04 \x01(\x0e2\r.ServerStatusR\x06status\x12\x12\n" +
	"\x04ipv4\x18\x05 \x01(\tR\x04ipv4\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x0e\n" +
	"\x02os\x18\b \x01(\tR\x02os\x12#\n" +
	"\rinterval_time\x18\t \x01(\x03R\fintervalTime\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xbe\x01\n" +
	"\x17ServerListFilterOptions\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12%\n" +
	"\x06status\x18\x03 \x01(\x0e2\r.ServerStatusR\x06status\x12\x12\n" +
	"\x04ipv4\x18\x04 \x01(\tR\x04ipv4\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x0e\n" +
	"\x02os\x18\x06 \x01(\tR\x02os\"y\n" +
	"\x14ServerListPagination\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x123\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\v2\x14.ServerListSortOrderR\tsortOrder\"\xc3\x01\n" +
	"\x13CreateServerRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12\x12\n" +
	"\x04ipv4\x18\x03 \x01(\tR\x04ipv4\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x0e\n" +
	"\x02os\x18\x05 \x01(\tR\x02os\x12.\n" +
	"\x13interval_check_time\x18\x06 \x01(\rR\x11intervalCheckTime\"&\n" +
	"\x14CreateServerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xaf\x01\n" +
	"\x11ViewServerRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x120\n" +
	"\x06filter\x18\x03 \x01(\v2\x18.ServerListFilterOptionsR\x06filter\x12:\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x0e2\x1b.ServerListSortOrder.ValuesR\tsortOrder\"X\n" +
	"\x12ViewServerResponse\x12!\n" +
	"\aservers\x18\x01 \x03(\v2\a.ServerR\aservers\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\rR\n" +
	"totalCount\"\xa6\x01\n" +
	"\x13UpdateServerRequest\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12\x12\n" +
	"\x04ipv4\x18\x02 \x01(\tR\x04ipv4\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12.\n" +
	"\x13interval_check_time\x18\x05 \x01(\rR\x11intervalCheckTime\"7\n" +
	"\x14UpdateServerResponse\x12\x1f\n" +
	"\x06server\x18\x01 \x01(\v2\a.ServerR\x06server\"2\n" +
	"\x13DeleteServerRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"0\n" +
	"\x14DeleteServerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"9\n" +
	"\x14ImportServersRequest\x12!\n" +
	"\aservers\x18\x01 \x03(\v2\a.ServerR\aservers\"\xa3\x01\n" +
	"\x15ImportServersResponse\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\rR\fsuccessCount\x12\x1f\n" +
	"\vsuccess_ids\x18\x02 \x03(\tR\n" +
	"successIds\x12#\n" +
	"\rfailure_count\x18\x03 \x01(\rR\ffailureCount\x12\x1f\n" +
	"\vfailure_ids\x18\x04 \x03(\tR\n" +
	"failureIds\"H\n" +
	"\x14ExportServersRequest\x120\n" +
	"\x06filter\x18\x01 \x01(\v2\x18.ServerListFilterOptionsR\x06filter\":\n" +
	"\x15ExportServersResponse\x12!\n" +
	"\aservers\x18\x01 \x03(\v2\a.ServerR\aservers*w\n" +
	"\fServerStatus\x12\x1d\n" +
	"\x19SERVER_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SERVER_STATUS_ON\x10\x01\x12\x15\n" +
	"\x11SERVER_STATUS_OFF\x10\x02\x12\x1b\n" +
	"\x17SERVER_STATUS_UNDEFINED\x10\x032\x89\x03\n" +
	"\rServerService\x12=\n" +
	"\fCreateServer\x12\x14.CreateServerRequest\x1a\x15.CreateServerResponse\"\x00\x127\n" +
	"\n" +
	"ViewServer\x12\x12.ViewServerRequest\x1a\x13.ViewServerResponse\"\x00\x12=\n" +
	"\fUpdateServer\x12\x14.UpdateServerRequest\x1a\x15.UpdateServerResponse\"\x00\x12=\n" +
	"\fDeleteServer\x12\x14.DeleteServerRequest\x1a\x15.DeleteServerResponse\"\x00\x12@\n" +
	"\rImportServers\x12\x15.ImportServersRequest\x1a\x16.ImportServersResponse\"\x00\x12@\n" +
	"\rExportServers\x12\x15.ExportServersRequest\x1a\x16.ExportServersResponse\"\x00B\x17Z\x15/proto/server_serviceb\x06proto3"

var (
	file_proto_server_service_server_service_proto_rawDescOnce sync.Once
	file_proto_server_service_server_service_proto_rawDescData []byte
)

func file_proto_server_service_server_service_proto_rawDescGZIP() []byte {
	file_proto_server_service_server_service_proto_rawDescOnce.Do(func() {
		file_proto_server_service_server_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_server_service_server_service_proto_rawDesc), len(file_proto_server_service_server_service_proto_rawDesc)))
	})
	return file_proto_server_service_server_service_proto_rawDescData
}

var file_proto_server_service_server_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_server_service_server_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_server_service_server_service_proto_goTypes = []any{
	(ServerStatus)(0),               // 0: ServerStatus
	(ServerListSortOrder_Values)(0), // 1: ServerListSortOrder.Values
	(*ServerListSortOrder)(nil),     // 2: ServerListSortOrder
	(*Server)(nil),                  // 3: Server
	(*ServerListFilterOptions)(nil), // 4: ServerListFilterOptions
	(*ServerListPagination)(nil),    // 5: ServerListPagination
	(*CreateServerRequest)(nil),     // 6: CreateServerRequest
	(*CreateServerResponse)(nil),    // 7: CreateServerResponse
	(*ViewServerRequest)(nil),       // 8: ViewServerRequest
	(*ViewServerResponse)(nil),      // 9: ViewServerResponse
	(*UpdateServerRequest)(nil),     // 10: UpdateServerRequest
	(*UpdateServerResponse)(nil),    // 11: UpdateServerResponse
	(*DeleteServerRequest)(nil),     // 12: DeleteServerRequest
	(*DeleteServerResponse)(nil),    // 13: DeleteServerResponse
	(*ImportServersRequest)(nil),    // 14: ImportServersRequest
	(*ImportServersResponse)(nil),   // 15: ImportServersResponse
	(*ExportServersRequest)(nil),    // 16: ExportServersRequest
	(*ExportServersResponse)(nil),   // 17: ExportServersResponse
	(*timestamppb.Timestamp)(nil),   // 18: google.protobuf.Timestamp
}
var file_proto_server_service_server_service_proto_depIdxs = []int32{
	0,  // 0: Server.status:type_name -> ServerStatus
	18, // 1: Server.created_at:type_name -> google.protobuf.Timestamp
	0,  // 2: ServerListFilterOptions.status:type_name -> ServerStatus
	2,  // 3: ServerListPagination.sort_order:type_name -> ServerListSortOrder
	4,  // 4: ViewServerRequest.filter:type_name -> ServerListFilterOptions
	1,  // 5: ViewServerRequest.sort_order:type_name -> ServerListSortOrder.Values
	3,  // 6: ViewServerResponse.servers:type_name -> Server
	3,  // 7: UpdateServerResponse.server:type_name -> Server
	3,  // 8: ImportServersRequest.servers:type_name -> Server
	4,  // 9: ExportServersRequest.filter:type_name -> ServerListFilterOptions
	3,  // 10: ExportServersResponse.servers:type_name -> Server
	6,  // 11: ServerService.CreateServer:input_type -> CreateServerRequest
	8,  // 12: ServerService.ViewServer:input_type -> ViewServerRequest
	10, // 13: ServerService.UpdateServer:input_type -> UpdateServerRequest
	12, // 14: ServerService.DeleteServer:input_type -> DeleteServerRequest
	14, // 15: ServerService.ImportServers:input_type -> ImportServersRequest
	16, // 16: ServerService.ExportServers:input_type -> ExportServersRequest
	7,  // 17: ServerService.CreateServer:output_type -> CreateServerResponse
	9,  // 18: ServerService.ViewServer:output_type -> ViewServerResponse
	11, // 19: ServerService.UpdateServer:output_type -> UpdateServerResponse
	13, // 20: ServerService.DeleteServer:output_type -> DeleteServerResponse
	15, // 21: ServerService.ImportServers:output_type -> ImportServersResponse
	17, // 22: ServerService.ExportServers:output_type -> ExportServersResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_server_service_server_service_proto_init() }
func file_proto_server_service_server_service_proto_init() {
	if File_proto_server_service_server_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_server_service_server_service_proto_rawDesc), len(file_proto_server_service_server_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_server_service_server_service_proto_goTypes,
		DependencyIndexes: file_proto_server_service_server_service_proto_depIdxs,
		EnumInfos:         file_proto_server_service_server_service_proto_enumTypes,
		MessageInfos:      file_proto_server_service_server_service_proto_msgTypes,
	}.Build()
	File_proto_server_service_server_service_proto = out.File
	file_proto_server_service_server_service_proto_goTypes = nil
	file_proto_server_service_server_service_proto_depIdxs = nil
}
