server:
  host: "0.0.0.0"
  port: 8081

postgres:
  host: postgres
  port: 5432
  user: postgres
  password: password
  dbname: vcs_sms
  max_open_conns: 100
  max_idle_conns: 10

logger:
  level: info
  file_path: ./logs/server_service.log
  max_size: 100
  max_backups: 10
  max_age: 30