server:
  name: ViettelSMS_ServerService
  env: development
  port: 8080

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: password
  dbname: vcs_sms
  max_idle_conns: 10
  max_open_conns: 100

log:
  level: info
  file_path: ./logs/app.log
  max_size: 100
  max_backups: 10
  max_age: 30

broker:
  addresses:
    - localhost:9092
  client_id: vcs_sms

cache:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 10

elasticsearch:
  url: http://localhost:9200

cron:
  update_status:
    name: "update_status"
    schedule: "@every 5s"  
  daily_report:
    name: "daily_report"
    schedule: "0 0 8 * * *"

dispatcher:
  process_interval: 20s
  lock_checker_interval: 600m
  cleanup_worker_interval: 60s
  max_lock_time_duration: 5m
  messages_retention_duration: 1m
  machine_id: "machine-1"
  retrial_policy:
    max_send_attempts_enabled: true
    max_send_attempts: 3
  