grpc:
  host: "0.0.0.0"
  port: 8080

postgres:
  host: postgres
  port: 5432
  user: postgres
  password: password
  dbname: vcs_sms
  max_idle_conns: 10
  max_open_conns: 100

server_service:
  host: "0.0.0.0"
  port: 50053

log:
  level: info
  file_path: ./logs/app.log
  max_size: 100
  max_backups: 10
  max_age: 30