// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package application

import (
	"github.com/th1enq/ViettelSMS_ServerService/internal/config"
	"github.com/th1enq/ViettelSMS_ServerService/internal/delivery/http"
	"github.com/th1enq/ViettelSMS_ServerService/internal/infrastucture/logger"
)

// Injectors from wire.go:

func InitApp() (*Application, error) {
	configConfig := config.LoadConfig()
	logger, err := log.LoadLogger(configConfig)
	if err != nil {
		return nil, err
	}
	serverInterface := http.NewHttpServer(configConfig, logger)
	application := NewApplication(serverInterface, logger)
	return application, nil
}
